<div class="page-title-wrapper">
    <h1 class="page-title">
        <span class="base" data-ui-id="page-title-wrapper">Thank you for your purchase!</span>    </h1>
    
   
   




<div class="checkout-success">
                        <p>Your order number is: <a href="https://wpuat.tk/sales/order/view/order_id/2460/" class="order-number"><strong>000002882</strong></a>.</p>
                    <p>We'll email you an order confirmation with details and tracking info.</p>
    
    
    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="#"><span>Continue Shopping</span></a>
        </div>
    </div>
</div>
     </div>
